### ISSUE TITLE
Lookup for NS on every user

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/volterra-onboarding#23]
Current logic makes an API call for every user in the group to see if they have an existing namespace.  recommend that we alter this logic to only perform this task if the user does not exist in the Volterra userCache.

**Comment by kreynoldsf5** [comment]
It is possible for a user to be in the userCache but not have a namespace. 

You make a good point. I'll include a list of namespaces in a generic cache object along with available users. We'll then hold onto that object for the duration of a session or to a fixed expiry (already implemented this for the userCache).

I think this should be included in the session reuse issue. 

@codygreen thoughts?

**Comment by codygreen** [comment]
I like it!

**Comment by kreynoldsf5** [comment]
This has been corrected.
